version: '3'

services:
  app:
    container_name: marketanalyzer-indicators
    build: .
    volumes:
      - .:/go/src/
    ports:
      - '50051:50051'
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
