// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: protofile/indicators.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MacdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data         []float64 `protobuf:"fixed64,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	FastPeriod   int32     `protobuf:"varint,2,opt,name=fastPeriod,proto3" json:"fastPeriod,omitempty"`
	SlowPeriod   int32     `protobuf:"varint,3,opt,name=slowPeriod,proto3" json:"slowPeriod,omitempty"`
	SignalPeriod int32     `protobuf:"varint,4,opt,name=signalPeriod,proto3" json:"signalPeriod,omitempty"`
	Initial      bool      `protobuf:"varint,5,opt,name=initial,proto3" json:"initial,omitempty"`
}

func (x *MacdRequest) Reset() {
	*x = MacdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_indicators_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MacdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MacdRequest) ProtoMessage() {}

func (x *MacdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_indicators_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MacdRequest.ProtoReflect.Descriptor instead.
func (*MacdRequest) Descriptor() ([]byte, []int) {
	return file_protofile_indicators_proto_rawDescGZIP(), []int{0}
}

func (x *MacdRequest) GetData() []float64 {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MacdRequest) GetFastPeriod() int32 {
	if x != nil {
		return x.FastPeriod
	}
	return 0
}

func (x *MacdRequest) GetSlowPeriod() int32 {
	if x != nil {
		return x.SlowPeriod
	}
	return 0
}

func (x *MacdRequest) GetSignalPeriod() int32 {
	if x != nil {
		return x.SignalPeriod
	}
	return 0
}

func (x *MacdRequest) GetInitial() bool {
	if x != nil {
		return x.Initial
	}
	return false
}

type MacdReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FastLength   float64 `protobuf:"fixed64,1,opt,name=fastLength,proto3" json:"fastLength,omitempty"`
	Macd         float64 `protobuf:"fixed64,2,opt,name=macd,proto3" json:"macd,omitempty"`
	SignalLength float64 `protobuf:"fixed64,3,opt,name=signalLength,proto3" json:"signalLength,omitempty"`
}

func (x *MacdReturn) Reset() {
	*x = MacdReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_indicators_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MacdReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MacdReturn) ProtoMessage() {}

func (x *MacdReturn) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_indicators_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MacdReturn.ProtoReflect.Descriptor instead.
func (*MacdReturn) Descriptor() ([]byte, []int) {
	return file_protofile_indicators_proto_rawDescGZIP(), []int{1}
}

func (x *MacdReturn) GetFastLength() float64 {
	if x != nil {
		return x.FastLength
	}
	return 0
}

func (x *MacdReturn) GetMacd() float64 {
	if x != nil {
		return x.Macd
	}
	return 0
}

func (x *MacdReturn) GetSignalLength() float64 {
	if x != nil {
		return x.SignalLength
	}
	return 0
}

type MacdResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*MacdReturn `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *MacdResult) Reset() {
	*x = MacdResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_indicators_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MacdResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MacdResult) ProtoMessage() {}

func (x *MacdResult) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_indicators_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MacdResult.ProtoReflect.Descriptor instead.
func (*MacdResult) Descriptor() ([]byte, []int) {
	return file_protofile_indicators_proto_rawDescGZIP(), []int{2}
}

func (x *MacdResult) GetData() []*MacdReturn {
	if x != nil {
		return x.Data
	}
	return nil
}

type StochRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataHigh  []float64 `protobuf:"fixed64,1,rep,packed,name=dataHigh,proto3" json:"dataHigh,omitempty"`
	DataLow   []float64 `protobuf:"fixed64,2,rep,packed,name=dataLow,proto3" json:"dataLow,omitempty"`
	DataClose []float64 `protobuf:"fixed64,3,rep,packed,name=dataClose,proto3" json:"dataClose,omitempty"`
	Length    int32     `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	SmoothK   int32     `protobuf:"varint,5,opt,name=smoothK,proto3" json:"smoothK,omitempty"`
	SmoothD   int32     `protobuf:"varint,6,opt,name=smoothD,proto3" json:"smoothD,omitempty"`
	MAUse     int32     `protobuf:"varint,7,opt,name=mAUse,proto3" json:"mAUse,omitempty"`
	Initial   bool      `protobuf:"varint,8,opt,name=initial,proto3" json:"initial,omitempty"`
}

func (x *StochRequest) Reset() {
	*x = StochRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_indicators_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StochRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StochRequest) ProtoMessage() {}

func (x *StochRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_indicators_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StochRequest.ProtoReflect.Descriptor instead.
func (*StochRequest) Descriptor() ([]byte, []int) {
	return file_protofile_indicators_proto_rawDescGZIP(), []int{3}
}

func (x *StochRequest) GetDataHigh() []float64 {
	if x != nil {
		return x.DataHigh
	}
	return nil
}

func (x *StochRequest) GetDataLow() []float64 {
	if x != nil {
		return x.DataLow
	}
	return nil
}

func (x *StochRequest) GetDataClose() []float64 {
	if x != nil {
		return x.DataClose
	}
	return nil
}

func (x *StochRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *StochRequest) GetSmoothK() int32 {
	if x != nil {
		return x.SmoothK
	}
	return 0
}

func (x *StochRequest) GetSmoothD() int32 {
	if x != nil {
		return x.SmoothD
	}
	return 0
}

func (x *StochRequest) GetMAUse() int32 {
	if x != nil {
		return x.MAUse
	}
	return 0
}

func (x *StochRequest) GetInitial() bool {
	if x != nil {
		return x.Initial
	}
	return false
}

type StochReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Smoothk float64 `protobuf:"fixed64,1,opt,name=smoothk,proto3" json:"smoothk,omitempty"`
	Smoothd float64 `protobuf:"fixed64,2,opt,name=smoothd,proto3" json:"smoothd,omitempty"`
}

func (x *StochReturn) Reset() {
	*x = StochReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_indicators_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StochReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StochReturn) ProtoMessage() {}

func (x *StochReturn) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_indicators_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StochReturn.ProtoReflect.Descriptor instead.
func (*StochReturn) Descriptor() ([]byte, []int) {
	return file_protofile_indicators_proto_rawDescGZIP(), []int{4}
}

func (x *StochReturn) GetSmoothk() float64 {
	if x != nil {
		return x.Smoothk
	}
	return 0
}

func (x *StochReturn) GetSmoothd() float64 {
	if x != nil {
		return x.Smoothd
	}
	return 0
}

type StochResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*StochReturn `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *StochResult) Reset() {
	*x = StochResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_indicators_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StochResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StochResult) ProtoMessage() {}

func (x *StochResult) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_indicators_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StochResult.ProtoReflect.Descriptor instead.
func (*StochResult) Descriptor() ([]byte, []int) {
	return file_protofile_indicators_proto_rawDescGZIP(), []int{5}
}

func (x *StochResult) GetData() []*StochReturn {
	if x != nil {
		return x.Data
	}
	return nil
}

type DmiReturn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Adx    float64 `protobuf:"fixed64,1,opt,name=adx,proto3" json:"adx,omitempty"`
	Plusd  float64 `protobuf:"fixed64,2,opt,name=plusd,proto3" json:"plusd,omitempty"`
	Minusd float64 `protobuf:"fixed64,3,opt,name=minusd,proto3" json:"minusd,omitempty"`
}

func (x *DmiReturn) Reset() {
	*x = DmiReturn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_indicators_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DmiReturn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmiReturn) ProtoMessage() {}

func (x *DmiReturn) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_indicators_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmiReturn.ProtoReflect.Descriptor instead.
func (*DmiReturn) Descriptor() ([]byte, []int) {
	return file_protofile_indicators_proto_rawDescGZIP(), []int{6}
}

func (x *DmiReturn) GetAdx() float64 {
	if x != nil {
		return x.Adx
	}
	return 0
}

func (x *DmiReturn) GetPlusd() float64 {
	if x != nil {
		return x.Plusd
	}
	return 0
}

func (x *DmiReturn) GetMinusd() float64 {
	if x != nil {
		return x.Minusd
	}
	return 0
}

type DmiResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*DmiReturn `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *DmiResult) Reset() {
	*x = DmiResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_indicators_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DmiResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DmiResult) ProtoMessage() {}

func (x *DmiResult) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_indicators_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DmiResult.ProtoReflect.Descriptor instead.
func (*DmiResult) Descriptor() ([]byte, []int) {
	return file_protofile_indicators_proto_rawDescGZIP(), []int{7}
}

func (x *DmiResult) GetData() []*DmiReturn {
	if x != nil {
		return x.Data
	}
	return nil
}

type StandardDatasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataHigh  []float64 `protobuf:"fixed64,1,rep,packed,name=dataHigh,proto3" json:"dataHigh,omitempty"`
	DataLow   []float64 `protobuf:"fixed64,2,rep,packed,name=dataLow,proto3" json:"dataLow,omitempty"`
	DataClose []float64 `protobuf:"fixed64,3,rep,packed,name=dataClose,proto3" json:"dataClose,omitempty"`
	Length    int32     `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Initial   bool      `protobuf:"varint,5,opt,name=initial,proto3" json:"initial,omitempty"`
}

func (x *StandardDatasRequest) Reset() {
	*x = StandardDatasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_indicators_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StandardDatasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardDatasRequest) ProtoMessage() {}

func (x *StandardDatasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_indicators_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardDatasRequest.ProtoReflect.Descriptor instead.
func (*StandardDatasRequest) Descriptor() ([]byte, []int) {
	return file_protofile_indicators_proto_rawDescGZIP(), []int{8}
}

func (x *StandardDatasRequest) GetDataHigh() []float64 {
	if x != nil {
		return x.DataHigh
	}
	return nil
}

func (x *StandardDatasRequest) GetDataLow() []float64 {
	if x != nil {
		return x.DataLow
	}
	return nil
}

func (x *StandardDatasRequest) GetDataClose() []float64 {
	if x != nil {
		return x.DataClose
	}
	return nil
}

func (x *StandardDatasRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *StandardDatasRequest) GetInitial() bool {
	if x != nil {
		return x.Initial
	}
	return false
}

type StandardDatasOnlyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataHigh  []float64 `protobuf:"fixed64,1,rep,packed,name=dataHigh,proto3" json:"dataHigh,omitempty"`
	DataLow   []float64 `protobuf:"fixed64,2,rep,packed,name=dataLow,proto3" json:"dataLow,omitempty"`
	Increment float64   `protobuf:"fixed64,3,opt,name=increment,proto3" json:"increment,omitempty"`
	Maximum   float64   `protobuf:"fixed64,4,opt,name=maximum,proto3" json:"maximum,omitempty"`
	Initial   bool      `protobuf:"varint,5,opt,name=initial,proto3" json:"initial,omitempty"`
}

func (x *StandardDatasOnlyRequest) Reset() {
	*x = StandardDatasOnlyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_indicators_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StandardDatasOnlyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardDatasOnlyRequest) ProtoMessage() {}

func (x *StandardDatasOnlyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_indicators_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardDatasOnlyRequest.ProtoReflect.Descriptor instead.
func (*StandardDatasOnlyRequest) Descriptor() ([]byte, []int) {
	return file_protofile_indicators_proto_rawDescGZIP(), []int{9}
}

func (x *StandardDatasOnlyRequest) GetDataHigh() []float64 {
	if x != nil {
		return x.DataHigh
	}
	return nil
}

func (x *StandardDatasOnlyRequest) GetDataLow() []float64 {
	if x != nil {
		return x.DataLow
	}
	return nil
}

func (x *StandardDatasOnlyRequest) GetIncrement() float64 {
	if x != nil {
		return x.Increment
	}
	return 0
}

func (x *StandardDatasOnlyRequest) GetMaximum() float64 {
	if x != nil {
		return x.Maximum
	}
	return 0
}

func (x *StandardDatasOnlyRequest) GetInitial() bool {
	if x != nil {
		return x.Initial
	}
	return false
}

type StandardRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    []float64 `protobuf:"fixed64,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	Length  int32     `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Initial bool      `protobuf:"varint,3,opt,name=initial,proto3" json:"initial,omitempty"`
}

func (x *StandardRequest) Reset() {
	*x = StandardRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_indicators_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StandardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardRequest) ProtoMessage() {}

func (x *StandardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_indicators_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardRequest.ProtoReflect.Descriptor instead.
func (*StandardRequest) Descriptor() ([]byte, []int) {
	return file_protofile_indicators_proto_rawDescGZIP(), []int{10}
}

func (x *StandardRequest) GetData() []float64 {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StandardRequest) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *StandardRequest) GetInitial() bool {
	if x != nil {
		return x.Initial
	}
	return false
}

type StandardResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []float64 `protobuf:"fixed64,1,rep,packed,name=data,proto3" json:"data,omitempty"`
}

func (x *StandardResult) Reset() {
	*x = StandardResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofile_indicators_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StandardResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardResult) ProtoMessage() {}

func (x *StandardResult) ProtoReflect() protoreflect.Message {
	mi := &file_protofile_indicators_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardResult.ProtoReflect.Descriptor instead.
func (*StandardResult) Descriptor() ([]byte, []int) {
	return file_protofile_indicators_proto_rawDescGZIP(), []int{11}
}

func (x *StandardResult) GetData() []float64 {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_protofile_indicators_proto protoreflect.FileDescriptor

var file_protofile_indicators_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2f, 0x69, 0x6e, 0x64, 0x69,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x69, 0x6e,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x9f, 0x01, 0x0a, 0x0b, 0x4d, 0x61, 0x63,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a,
	0x66, 0x61, 0x73, 0x74, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x66, 0x61, 0x73, 0x74, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x6c, 0x6f, 0x77, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0a, 0x73, 0x6c, 0x6f, 0x77, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x64, 0x0a, 0x0a, 0x4d, 0x61,
	0x63, 0x64, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x61, 0x73, 0x74,
	0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x66, 0x61,
	0x73, 0x74, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x63, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x6d, 0x61, 0x63, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68,
	0x22, 0x38, 0x0a, 0x0a, 0x4d, 0x61, 0x63, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2a,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x69,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x4d, 0x61, 0x63, 0x64, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xde, 0x01, 0x0a, 0x0c, 0x53,
	0x74, 0x6f, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x61, 0x74, 0x61, 0x48, 0x69, 0x67, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x08, 0x64,
	0x61, 0x74, 0x61, 0x48, 0x69, 0x67, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x4c,
	0x6f, 0x77, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x6f,
	0x77, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6d, 0x6f, 0x6f, 0x74,
	0x68, 0x4b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x6d, 0x6f, 0x6f, 0x74, 0x68,
	0x4b, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x44, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x73, 0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x41, 0x55, 0x73, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x41, 0x55, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x41, 0x0a, 0x0b, 0x53,
	0x74, 0x6f, 0x63, 0x68, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6d,
	0x6f, 0x6f, 0x74, 0x68, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x73, 0x6d, 0x6f,
	0x6f, 0x74, 0x68, 0x6b, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x73, 0x6d, 0x6f, 0x6f, 0x74, 0x68, 0x64, 0x22, 0x3a,
	0x0a, 0x0b, 0x53, 0x74, 0x6f, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2b, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x6e,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x68, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4b, 0x0a, 0x09, 0x44, 0x6d,
	0x69, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x64, 0x78, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x61, 0x64, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6c, 0x75,
	0x73, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x6c, 0x75, 0x73, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x6d, 0x69, 0x6e, 0x75, 0x73, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x6d, 0x69, 0x6e, 0x75, 0x73, 0x64, 0x22, 0x36, 0x0a, 0x09, 0x44, 0x6d, 0x69, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e,
	0x44, 0x6d, 0x69, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x9c, 0x01, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x48, 0x69, 0x67, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x48, 0x69, 0x67, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x6f, 0x77, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x6f, 0x77, 0x12, 0x1c,
	0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x01, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x22, 0xa2,
	0x01, 0x0a, 0x18, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x73,
	0x4f, 0x6e, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x61, 0x74, 0x61, 0x48, 0x69, 0x67, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x08, 0x64,
	0x61, 0x74, 0x61, 0x48, 0x69, 0x67, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x61, 0x74, 0x61, 0x4c,
	0x6f, 0x77, 0x18, 0x02, 0x20, 0x03, 0x28, 0x01, 0x52, 0x07, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x6f,
	0x77, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x69, 0x6e, 0x63, 0x72, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x07, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x61, 0x6c, 0x22, 0x57, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x01, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x22, 0x24, 0x0a, 0x0e,
	0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x01, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x32, 0xfc, 0x04, 0x0a, 0x11, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x03, 0x45, 0x6d, 0x61, 0x12,
	0x1b, 0x2e, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61,
	0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x69,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x03, 0x53, 0x6d,
	0x61, 0x12, 0x1b, 0x2e, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x53,
	0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x6e,
	0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x04,
	0x4d, 0x61, 0x63, 0x64, 0x12, 0x17, 0x2e, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x73, 0x2e, 0x4d, 0x61, 0x63, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x4d, 0x61, 0x63, 0x64, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0f, 0x53, 0x74, 0x6f, 0x63, 0x68,
	0x4f, 0x73, 0x63, 0x69, 0x6c, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x2e, 0x69, 0x6e, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x73, 0x2e, 0x53, 0x74, 0x6f, 0x63, 0x68, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12,
	0x45, 0x0a, 0x03, 0x43, 0x63, 0x69, 0x12, 0x20, 0x2e, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x69, 0x6e, 0x64, 0x69, 0x63,
	0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x03, 0x41, 0x74, 0x72, 0x12, 0x20, 0x2e,
	0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64,
	0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61,
	0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x49, 0x0a,
	0x03, 0x53, 0x61, 0x72, 0x12, 0x24, 0x2e, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x73, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x73, 0x4f,
	0x6e, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x69, 0x6e, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x03, 0x44, 0x6d, 0x69, 0x12,
	0x20, 0x2e, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x53, 0x74, 0x61,
	0x6e, 0x64, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x15, 0x2e, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x44,
	0x6d, 0x69, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x03, 0x41, 0x64,
	0x78, 0x12, 0x20, 0x2e, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x2e, 0x53,
	0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73,
	0x2e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x00, 0x42, 0x09, 0x5a, 0x07, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protofile_indicators_proto_rawDescOnce sync.Once
	file_protofile_indicators_proto_rawDescData = file_protofile_indicators_proto_rawDesc
)

func file_protofile_indicators_proto_rawDescGZIP() []byte {
	file_protofile_indicators_proto_rawDescOnce.Do(func() {
		file_protofile_indicators_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofile_indicators_proto_rawDescData)
	})
	return file_protofile_indicators_proto_rawDescData
}

var file_protofile_indicators_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_protofile_indicators_proto_goTypes = []interface{}{
	(*MacdRequest)(nil),              // 0: indicators.MacdRequest
	(*MacdReturn)(nil),               // 1: indicators.MacdReturn
	(*MacdResult)(nil),               // 2: indicators.MacdResult
	(*StochRequest)(nil),             // 3: indicators.StochRequest
	(*StochReturn)(nil),              // 4: indicators.StochReturn
	(*StochResult)(nil),              // 5: indicators.StochResult
	(*DmiReturn)(nil),                // 6: indicators.DmiReturn
	(*DmiResult)(nil),                // 7: indicators.DmiResult
	(*StandardDatasRequest)(nil),     // 8: indicators.StandardDatasRequest
	(*StandardDatasOnlyRequest)(nil), // 9: indicators.StandardDatasOnlyRequest
	(*StandardRequest)(nil),          // 10: indicators.StandardRequest
	(*StandardResult)(nil),           // 11: indicators.StandardResult
}
var file_protofile_indicators_proto_depIdxs = []int32{
	1,  // 0: indicators.MacdResult.data:type_name -> indicators.MacdReturn
	4,  // 1: indicators.StochResult.data:type_name -> indicators.StochReturn
	6,  // 2: indicators.DmiResult.data:type_name -> indicators.DmiReturn
	10, // 3: indicators.IndicatorsService.Ema:input_type -> indicators.StandardRequest
	10, // 4: indicators.IndicatorsService.Sma:input_type -> indicators.StandardRequest
	0,  // 5: indicators.IndicatorsService.Macd:input_type -> indicators.MacdRequest
	3,  // 6: indicators.IndicatorsService.StochOscillator:input_type -> indicators.StochRequest
	8,  // 7: indicators.IndicatorsService.Cci:input_type -> indicators.StandardDatasRequest
	8,  // 8: indicators.IndicatorsService.Atr:input_type -> indicators.StandardDatasRequest
	9,  // 9: indicators.IndicatorsService.Sar:input_type -> indicators.StandardDatasOnlyRequest
	8,  // 10: indicators.IndicatorsService.Dmi:input_type -> indicators.StandardDatasRequest
	8,  // 11: indicators.IndicatorsService.Adx:input_type -> indicators.StandardDatasRequest
	11, // 12: indicators.IndicatorsService.Ema:output_type -> indicators.StandardResult
	11, // 13: indicators.IndicatorsService.Sma:output_type -> indicators.StandardResult
	2,  // 14: indicators.IndicatorsService.Macd:output_type -> indicators.MacdResult
	5,  // 15: indicators.IndicatorsService.StochOscillator:output_type -> indicators.StochResult
	11, // 16: indicators.IndicatorsService.Cci:output_type -> indicators.StandardResult
	11, // 17: indicators.IndicatorsService.Atr:output_type -> indicators.StandardResult
	11, // 18: indicators.IndicatorsService.Sar:output_type -> indicators.StandardResult
	7,  // 19: indicators.IndicatorsService.Dmi:output_type -> indicators.DmiResult
	11, // 20: indicators.IndicatorsService.Adx:output_type -> indicators.StandardResult
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_protofile_indicators_proto_init() }
func file_protofile_indicators_proto_init() {
	if File_protofile_indicators_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofile_indicators_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MacdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_indicators_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MacdReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_indicators_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MacdResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_indicators_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StochRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_indicators_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StochReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_indicators_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StochResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_indicators_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DmiReturn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_indicators_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DmiResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_indicators_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StandardDatasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_indicators_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StandardDatasOnlyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_indicators_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StandardRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofile_indicators_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StandardResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofile_indicators_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofile_indicators_proto_goTypes,
		DependencyIndexes: file_protofile_indicators_proto_depIdxs,
		MessageInfos:      file_protofile_indicators_proto_msgTypes,
	}.Build()
	File_protofile_indicators_proto = out.File
	file_protofile_indicators_proto_rawDesc = nil
	file_protofile_indicators_proto_goTypes = nil
	file_protofile_indicators_proto_depIdxs = nil
}
