// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IndicatorsServiceClient is the client API for IndicatorsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndicatorsServiceClient interface {
	Ema(ctx context.Context, in *StandardRequest, opts ...grpc.CallOption) (*StandardResult, error)
}

type indicatorsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndicatorsServiceClient(cc grpc.ClientConnInterface) IndicatorsServiceClient {
	return &indicatorsServiceClient{cc}
}

func (c *indicatorsServiceClient) Ema(ctx context.Context, in *StandardRequest, opts ...grpc.CallOption) (*StandardResult, error) {
	out := new(StandardResult)
	err := c.cc.Invoke(ctx, "/indicators.IndicatorsService/Ema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndicatorsServiceServer is the server API for IndicatorsService service.
// All implementations must embed UnimplementedIndicatorsServiceServer
// for forward compatibility
type IndicatorsServiceServer interface {
	Ema(context.Context, *StandardRequest) (*StandardResult, error)
	mustEmbedUnimplementedIndicatorsServiceServer()
}

// UnimplementedIndicatorsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIndicatorsServiceServer struct {
}

func (UnimplementedIndicatorsServiceServer) Ema(context.Context, *StandardRequest) (*StandardResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ema not implemented")
}
func (UnimplementedIndicatorsServiceServer) mustEmbedUnimplementedIndicatorsServiceServer() {}

// UnsafeIndicatorsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndicatorsServiceServer will
// result in compilation errors.
type UnsafeIndicatorsServiceServer interface {
	mustEmbedUnimplementedIndicatorsServiceServer()
}

func RegisterIndicatorsServiceServer(s grpc.ServiceRegistrar, srv IndicatorsServiceServer) {
	s.RegisterService(&IndicatorsService_ServiceDesc, srv)
}

func _IndicatorsService_Ema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StandardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndicatorsServiceServer).Ema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/indicators.IndicatorsService/Ema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndicatorsServiceServer).Ema(ctx, req.(*StandardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IndicatorsService_ServiceDesc is the grpc.ServiceDesc for IndicatorsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndicatorsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "indicators.IndicatorsService",
	HandlerType: (*IndicatorsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ema",
			Handler:    _IndicatorsService_Ema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protofile/indicators.proto",
}
